export const STRINGS = {
  home: 'خانه',
  topStories: 'برترین مطالب',
  recent: 'تازه‌ها',
  featured: 'ویژه',
  popular: 'پربازدید',
  moreArticles: 'مطالب بیشتر',
  by: 'نوشته',
  noArticles: 'هنوز مطلبی برای نمایش وجود ندارد.',
  search: 'جستجو',
  searchDescription: 'جستجو در مطالب مجله.',
  searchPlaceholder: 'جستجو...',
  searchNoResults: 'نتیجه‌ای یافت نشد',
  searchPrompt: 'عبارت مورد نظر را برای یافتن مطالب وارد کنید',
  sortBy: 'مرتب‌سازی',
  filterBy: 'فیلتر',
  newest: 'جدیدترین',
  oldest: 'قدیمی‌ترین',
  allCategories: 'همه دسته‌ها',
  contributors: 'نویسندگان',
  contributorsDescription: 'با نویسندگان و همکاران مجله آشنا شوید.',
  moreContributors: 'سایر نویسندگان',
  allContributions: 'همه مطالب',
  articlesBy: (name: string, role?: string) =>
    role ? `مطالب ${name}، ${role}` : `مطالب ${name}`,
  savedArticles: 'مطالب ذخیره‌شده',
  savedArticle: 'مطلب ذخیره‌شده',
  articleSaved: 'مطلب ذخیره شد!',
  articleRemoved: 'مطلب از لیست حذف شد!',
  noSavedArticles: 'هنوز مطلبی ذخیره نکرده‌اید.',
  saveArticlesHint: 'برای ذخیره مطالب، روی آیکون',
  saveArticlesHintEnd: 'بزنید.',
  loading: 'در حال بارگذاری...',
  somethingWentWrong: 'مشکلی پیش آمد',
  pageNotFound: '۴۰۴. صفحه یافت نشد',
  pageNotFoundDescription: 'متأسفانه این صفحه پیدا نشد.',
  offline: 'آفلاین هستید',
  offlineDescription: 'این صفحه قابل نمایش نیست چون به اینترنت متصل نیستید.',
  noInternet: 'اتصال اینترنت برقرار نیست',
  share: 'اشتراک‌گذاری',
  shareOnFacebook: 'اشتراک در فیسبوک',
  shareOnTwitter: 'اشتراک در توییتر',
  copiedToClipboard: 'در کلیپ‌بورد کپی شد!',
  checkThisArticle: 'این مطلب را ببینید',
  checkThisLink: 'این لینک را ببینید',
  exitPreview: 'خروج از حالت پیش‌نمایش',
  themeSystem: 'سیستم',
  themeDark: 'حالت تاریک',
  themeLight: 'حالت روشن',
  sections: 'بخش‌ها',
  about: 'درباره',
  more: 'بیشتر',
  contact: 'تماس با ما',
  contactDescription: 'از طریق فرم زیر با ما در ارتباط باشید.',
  fullName: 'نام و نام خانوادگی',
  mobileNumber: 'شماره همراه',
  message: 'متن پیام',
  sendMessage: 'ارسال پیام',
  contactSuccess: 'پیامتون رو میخونیم و باهاتون تماس میگیریم',
  contactError: 'ارسال پیام با مشکل مواجه شد. دوباره تلاش کنید.',
  other: 'سایر',
  featuredLinks: 'منتخب‌ها',
  footerRights: 'تمامی حقوق محفوظ است.',
  goBack: 'بازگشت',
  addToList: 'افزودن به لیست',
  myBookmarks: 'نشان‌شده‌های من',
  closeSearch: 'بستن جستجو',
  clinicManagementSystem: 'سامانه مدیریت کلینیک',
  developerTeam: 'تیم توسعه دهنده',
  close: 'بستن',
  copyToClipboard: 'کپی در کلیپ‌بورد',
  linkTo: (title: string) => `لینک به ${title}`,
  articleCount: (count: number) => `${count.toLocaleString('fa-IR')} مطلب`,
  searchResultCount: (count: number) =>
    `${count.toLocaleString('fa-IR')} نتیجه`,
} as const
